version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/S3Vendor_go"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "github-actions"
