steps:
  - label: "Julia {{matrix.julia}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1: ~
    agents:
      queue: "juliaecosystem"
      os: "linux"
      arch: "x86_64"
    timeout_in_minutes: 15
    matrix:
      setup:
        julia:
          - "1.6"
          - "1.7"
          - "1.8"
          - "1.9"
          - "1.10"
          - "1.11"
          - "nightly"
      adjustments:
        - with:
            julia: "nightly"
          soft_fail: true
